/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.0.1.0 (NJsonSchema v10.0.19.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export class CustomerBasic {
    id: number;
    name: string;
}

export class CustomerDetails extends CustomerBasic {
    company: CompanyBasic;
    shipNumber: number;
}

export class CompanyBasic {
    id: number;
    name: string;
}

export class ApiError {
    code: number;
    message: string;
}

export class SearchOrder {
    orderBy: string;
    orderDirection: string;
}

export class BaseQuery {
    id: number;
    locale: string;
}

export class CustomerQuery extends BaseQuery {
    name: string;
}

export class ShipBasic {
    id: number;
    name: string;
    imd: number;
    mmsi: number;
    aisVesselType: AisVesselType;
    rowVersion: string;
    aisVesselTypeLabel: string;
}

export class ShipDetails extends ShipBasic {
    customer: CustomerBasic;
    company: CompanyBasic;
    criticalEquipmentsNum: number;
}

export enum AisVesselType {
    Other = 0, 
}

export class BaseCommand {
    rowVersion: string;
}

export class ShipCommand extends BaseCommand {
    id: number;
    name: string;
    date: Date;
    imd: number;
    mmsi: number;
    customerId: number;
}


export class ShipListItem extends ShipBasic {
    customer: CustomerBasic;
    company: CompanyBasic;
    criticalEquipmentsNum: number;
}

export class ShipQuery extends BaseQuery {
    name: string;
    imd: number;
    mmsi: number;
    monthReportDate: Date;
}


export class ShipMonthReport extends ShipBasic {
    newEquipmentNum: number;
    updatedEquipmentNum: number;
}

export class LoginCommand {
    email: string;
    password: string;
}

export class RegisterDto {
    email: string;
    password: string;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}